config/urls.py
"""config URL Configuration
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.NewsIndex.as_view(), name='index'),
    path('category/<tag>/', views.Category.as_view(), name='category'),
]

news/models.py
from datetime import datetime, timedelta
from django.db import models
from django.utils.timezone import make_aware, now
from taggit.managers import TaggableManager
from .rss_parser import FeedItem

GMP_IRAN_TIMEZONE = timedelta(hours=4, minutes=30)


class New(models.Model):
    title = models.CharField(
        max_length=256,
        unique=True
    )
    pub_date = models.DateTimeField()
    link = models.URLField(
        unique=True
    )
    thumbnail = models.URLField(
        unique=True
    )
    description = models.TextField()
    categories = TaggableManager()

    @staticmethod
    def create_new(new_item: FeedItem):
        title = new_item.title.strip()
        # extract and set published date
        pub_date = New.convert_date(new_item.pub_date)
        link = new_item.link.strip()
        thumbnail = new_item.thumbnail.strip()
        description = new_item.description
        # create object
        new: New = New.objects.create(
            title=title,
            pub_date=pub_date,
            link=link,
            thumbnail=thumbnail,
            description=description
        )
        # add categories
        categories = New.set_categories(
            New.replace_category(new_item.categories)
        )
        categories = list(filter(
            lambda category: "،" not in category,
            categories
        ))
        if categories:
            new.categories.add(*categories)
        new.save()

    @staticmethod
    def convert_date(date: str) -> datetime:
        # sample date: Fri, 05 Aug 2022 06:45:15 GMT
        try:
            pub_date = datetime.strptime(date, "%a, %d %b %Y %H:%M:%S %Z")
        except ValueError:
            return now()
        if "+0430" not in date:
            pub_date = pub_date + GMP_IRAN_TIMEZONE
        pub_date = make_aware(pub_date)
        return pub_date

    @staticmethod
    def set_categories(categories: str) -> list:
        if ">" in categories:
            sep = ">"
        elif " و " in categories:
            sep = " و "
        else:
            sep = None
        if sep is not None:
            return list(map(
                str.strip,
                categories.split(sep)
            ))
        return [categories]

    @staticmethod
    def replace_category(input_categories: str):
        replaces = {
            ("اخبار استان ها", "استانها"): "استان‌ها",
            ("سایر ورزشها", "جهان ورزش", "دیگر ورزش‌ها", "ورزشی"): "ورزش",
            ("فوتبال ملی",): "فوتبال ایران",
        }
        for categories in replaces.keys():
            for category in categories:
                input_categories = input_categories.replace(
                    category,
                    replaces[categories]
                )
        return input_categories

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-pub_date',)

news/views.py
from django.shortcuts import get_object_or_404
from django.views.generic.list import ListView
from taggit.models import Tag
from .models import New


class NewsIndex(ListView):
    model = New
    paginate_by = 8
    context_object_name = 'news'
    template_name = 'news/news.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'categories': Tag.objects.filter(
                show_tag=True
            ).exclude(
                showing=False
            ).order_by('name'),
            'label': 'آخرین اخبار'
        })
        return context

    def get_queryset(self):
        return New.objects.exclude(
            categories__showing=False
        ).order_by('-pub_date')


class Category(ListView):
    model = New
    paginate_by = 8
    context_object_name = 'news'
    template_name = 'news/news.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = self.kwargs['tag']
        tag_object = get_object_or_404(Tag, slug=tag)
        context.update({
            'categories': Tag.objects.filter(
                show_tag=True
            ).exclude(
                showing=False
            ).order_by('name'),
            'label': tag_object.name
        })
        return context

    def get_queryset(self):
        tag = self.kwargs['tag']
        tag_object = get_object_or_404(Tag, slug=tag)
        return New.objects.filter(
            categories__slug=tag_object.slug
        ).exclude(
            categories__showing=False
        ).order_by('-pub_date')

news/templates/news/index.html
{% load static %}
{% load jalali_tags %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>وبسایت خبری</title>
    <!-- favicon -->
    <link
      rel="shortcut icon"
      href="{% static 'imgs/favicon.ico' %}"
      type="image/x-icon"
    />
    <!-- Bootstrap CS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Local CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'news:index' %}">وبسایت خبری</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">خانه</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                دسته بندی
              </a>
              <ul class="dropdown-menu">
                {% for tag in tags %}
                <li>
                  <a class="dropdown-item" href="{{ tag.slug }}">{{ tag }}</a>
                </li>
                {% endfor %}
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">درباره من</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="head container-fluid">
      <h3>
        <span class="badge text-bg-secondary">آخرین اخبار</span>
      </h3>
      <span class="line"></span>
    </div>
    <div id="newsBox" class="container-fluid">
      {% for new in news %}
        <div class="newsCard card">
          <img
            src="{{ new.thumbnail }}"
            class="img ard-img-top img-thumbnail"
            alt="{{ new.title }}"
          />
          <h5 class="card-header">{{ new.title }}</h5>
          <div class="card-body">
            <h5 class="card-text categories">
              {% for category in new.categories.all %}
                <a class="badge text-bg-secondary" href="{{ category.slug }}">
                  {{ category }}
                </a>
              {% endfor %}
            </h5>
            <p class="card-text">{{ new.description }}</p>
            <a
              target="_blank"
              href="{{ new.link }}"
              class="btn btn-primary"
              >بیشتر ...
            </a>
          </div>
          <div class="text-center card-footer text-muted">{{ new.pub_date|to_jalali:'%H:%M - %Y/%m/%d' }}</div>
        </div>
      {% endfor %}
      </div>
    </div>
    <footer id="sticky-footer" class="flex-shrink-0 py-2 bg-dark text-white-50">
      <div class="container-fluid text-center">
        <small>کپی رایت &copy; 2022 محمد دری</small>
      </div>
    </footer>
    <script src="{% static 'js/bootstrap.js' %}"></script>
  </body>
</html>

news/templates/news/news.html
{% load static %}
{% load jalali_tags %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>خبرگزاری آپتو</title>
    <link
      rel="shortcut icon"
      href="{% static 'imgs/favicon.ico' %}"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'news:index' %}">
          <img
            src="{% static 'imgs/icon.svg' %}"
            alt=""
            width="30"
            class="d-inline-block align-text-top ms-1 logo"
          />
          خبرگزاری آپتو
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a
                class="nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}"
                aria-current="page"
                href="{% url 'news:index' %}"
                >آخرین اخبار</a
              >
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link {% if request.resolver_match.url_name == 'category' %}active{% endif %} dropdown-toggle"
                href=""
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                دسته بندی
              </a>
              <ul class="dropdown-menu">
                {% for category in categories %}
                <li>
                  <a
                    class="dropdown-item"
                    href="{% url 'news:category' category.slug %}"
                    >{{ category }}</a
                  >
                </li>
                {% endfor %}
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="head container-fluid">
      <h3>
        <span class="badge text-bg-secondary">{{ label }}</span>
      </h3>
      <span class="line"></span>
    </div>
    <div id="newsBox" class="container-fluid infinite-container">
      {% for new in news %}
        <div class="newsCard card infinite-item">
          <img
            src="{{ new.thumbnail }}"
            class="img ard-img-top img-thumbnail"
            alt="{{ new.title }}"
          />
          <h5 class="card-header">{{ new.title }}</h5>
          <div class="card-body">
            <h5 class="card-text categories">
              {% for category in new.categories.all %}
              <a
                class="badge text-bg-secondary"
                href="{% url 'news:category' category.slug %}">
                {{ category }}
              </a>
              {% endfor %}
            </h5>
            <p class="card-text">{{ new.description }}</p>
          </div>
          <div class="text-center card-footer text-muted">
            {{ new.pub_date|to_jalali:'%H:%M - %Y/%m/%d' }}
          </div>
        </div>
      {% endfor %}
      {% if page_obj.has_next %}
        <a
          class="infinite-more-link"
          href="?page={{ page_obj.next_page_number }}">
        </a>
      {% endif %}
    </div>
    <footer id="sticky-footer" class="flex-shrink-0 py-1 bg-dark footer">
      <div class="container-fluid text-center">
        <small>
          آپتو ۲۰۲۲ &copy; توسط
          <a target="_blank" href="https://github.com/dori-dev">محمد دری</a>
        </small>
      </div>
    </footer>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script>
    <script>
      var infinite = new Waypoint.Infinite({
        element: $(".infinite-container")[0],
        handler: function (direction) {},
        offset: "bottom-in-view",
        onBeforePageLoad: function () {
          $(".spinner-border").show();
        },
        onAfterPageLoad: function () {
          $(".spinner-border").hide();
        },
      });
    </script>
  </body>
</html>